// 宣传语提案（中文修订版，2026-10-07）— app/projects/stake-video/taglines/page.tsx + components/StakeTaglines.tsx.
// Source: bulu-stake-video docs/15-tagline-cn-revision.md. Edit text here directly if needed.

export type Tier = 'lean' | 'keep' | 'alt' | 'ref'
export type Risk = 'low' | 'mid' | 'high'
export type Paths = 'both' | 'native' | 'liquid' | 'n/a'

export interface TaglineCategory {
  key: string
  title: string
  en: string
  desc: string
  color: string
}

export interface Tagline {
  id: string
  category: string
  cn: string // empty = the original has no Chinese line
  en: string
  subCn: string
  subEn: string
  idea: string
  fit: string
  risk: string
  compliance: Risk
  uses: string[]
  paths: Paths
  tier: Tier
  boss: boolean
  revisedFrom: string // headline in the previous round, empty = new
  changeNote: string
}

export interface Benchmark {
  group: 'cn' | 'global' | 'own'
  brand: string
  line: string
  note: string
  takeaway: string
  url: string
}

export const tierLabel: Record<Tier, string> = { lean: '当前倾向', keep: '值得保留', alt: '备选', ref: '参考' }
export const riskLabel: Record<Risk, string> = { low: '合规风险低', mid: '合规风险中', high: '合规风险高' }
export const pathLabel: Record<Paths, string> = { both: '两种质押方式都成立', native: '只适用于部分质押方式', liquid: '只适用于部分质押方式', 'n/a': '' }

export const stats = [
  { value: '17', label: '条修订后的提案，另附同事的 5 个主题' },
  { value: '5', label: '类，按讲故事的角度分' },
  { value: '16', label: '条竞品原文，逐条打开链接核对' },
  { value: '4', label: '条从「为网络工作，也为你工作」出发' },
]

export const bossLens = {
  reading: '质押的 ETH 同时在做两份工作：一份为以太坊，用自己做保证金，让网络更可靠；一份为持有它的人。宣传语里，「也为你」只落在三件事上：私钥还在你手里，要不要质押由你决定，你看好以太坊这么多年终于有了落点。',
  guardrail: '「为你工作」不能写成让钱替你打工、躺赚、被动收入，不出现收益、回报和任何比率，也不暗示用户自己在运行以太坊。老板的原句只是出发点，不直接拿来用。',
}

// Wilson 2026-10-07
export const decisions = [
  '「出力的是 ETH，做主的是你」不放进当前倾向，降为备选。',
  '片中旁白「ETH 不离开你的钱包，也能工作」不改。',
  '副标不写「不用卖」，太口语。',
  '片尾英文 Stake, Under Your Control 先不改。',
]

export const v1Issues = [
  '先有英文、再回译成中文，句子里留着英文句法：冒号揭晓（「它只认一个钱包：你的」= Yours.）、名词短语单独成句（「一样的长期持有。」）、「这些年……现在……」「这一次……」开头、「成为它的一部分」（be part of it）、「还能做更多」（do more，后面没有宾语）。',
  '「你的」用得太多：48 行主副标里有 23 行带「你的」，还有「你自己的钱包」这种「你」和「自己」重复的写法，读着像说明书或客服话术。副标也是一个模子，「在 imToken 质押你的 ETH」出现了 12 次。',
  '公文腔和新华体：「为……出一份力」出现 5 次，「一头连着……一头连着……」是央媒高频句式，「从信念，到共识」像年报口号墙，「为以太坊的安全与共识背书」是名词并列加公文动词。',
  '币圈语义踩雷：「站岗」就是高位被套；「守着」会读成被套硬扛；「共识」在圈内多指撑价格的叙事；「躺着」让人想到躺赚、躺平；「闲置」冒犯长期持有者；「有分量」配鲸鱼会读成大户才算数；「背书」接近担保；「没放过手」有「饶过」的歧义。',
  '主语和指代不清：主副标里一共 16 个「它」，有的主标直接以「它」开头；「从没卖过，从此醒着」前后半句主语不同，会被读成用户自己失眠、天天看盘。',
  '说明书腔：「托管方」「协议奖励」「以 ETH 计」「中间不经过任何托管方」「持有的天数照常往上数」都在解释机制，不在讲故事，和「专业感靠用词，不靠机制细节」相反。',
  '长度和标点不统一：4 条主标超过 12 字，副标普遍 25–40 字，放不进 Push 和 KV 第二行；有的主标带句号，有的不带。',
  '和同行拉不开距离的地方没有抓住：竞品的 ETH 质押主标几乎全是收益率和促销，imToken 只能靠故事（Bulu 和沉睡的 ETH）和对长期持有者的认同来区分，上一版有一部分条目反而在用同行的词（「闲置」「动起来」「做更多」「复利」）。',
]

export const principles: { title: string; desc: string }[] = [
  { title: '说人话', desc: '主标要能念出口、能被复述，像对朋友说的一句话。写完大声念一遍，念着拗口或像译文的就重写。' },
  { title: '主标短，副标补事实', desc: '主标 6–12 字，最多一个停顿，句末不加标点；副标尽量不超过 20 字，补上「imToken 质押」和私钥、交易所这类事实。旁白句可以长，主标要收短。' },
  { title: '主语清楚，少用「你的」和「它」', desc: '每句「你的」最多一次，主标不以「它」开头。记忆点靠同字呼应（看好 / 看着、几年 / 几年、这一颗 / 这一颗），不写 4+4 成语对联。' },
  { title: '先讲故事，专业感靠用词', desc: '只写画面里看得见的东西（睡、醒、一颗、光带、钥匙）和持有者的时间感；不解释验证、门槛和复利，这些留给 PR 正文和 FAQ。' },
  { title: '「也为你」只落在归属、决定权和信念', desc: '老板的「为网络工作，也为你工作」可以写，但「为你」只写私钥在你手里、你来做主、你的看好有了落点；不写赚、收益、生息、被动收入，不给任何比率，奖励只叫「质押奖励」。' },
  { title: '非托管讲私钥和控制权', desc: '宣传语里说「私钥不交出去」「不用先充进交易所」，两种质押方式都要成立，必要时用「资产」代替「ETH」。片中旁白「ETH 不离开你的钱包，也能工作」保持不变（Wilson 10/07），宣传语不再另造类似的位置描述。' },
  { title: '绕开币圈和金融的雷区词', desc: '不用站岗、拿住（社媒以外）、钻石手、囤币、躺、闲置、穿越牛熊、安全、保证、锁定、随时可取；PR 标题不把「鲸」和「醒」连用，避开「沉睡巨鲸苏醒」的抛售新闻句式。' },
  { title: '面向全球简体中文用户', desc: '简体中文不等于面向中国大陆：不出现人民币计价、境内渠道这类定向表述，投放地区和渠道由法务确认。' },
]

export const benchmarks: Benchmark[] = [
  { group: 'cn', brand: '欧易 OKX（赚币）', line: '持币生息，安全无忧', note: '', takeaway: '交易所主标的标准写法：4+4 对仗，前半句给利益、后半句给保障；「生息」「安全无忧」正好都在我们的红线上，不跟。', url: 'https://www.okx.com/zh-hans/earn' },
  { group: 'cn', brand: '币安 Binance（ETH 质押）', line: '收益每天赚，机会不间断', note: '页面防抓取，按网页文字提取核对', takeaway: '用「每天」「不间断」强调回报频率，核心动词是「赚」；我们不在这条赛道上比，改讲长期持有者的时间感。', url: 'https://www.binance.com/zh-CN/eth2' },
  { group: 'cn', brand: 'Gate（链上赚币）', line: '链上精选，质押赚币', note: '页面 H2，H1 是「链上赚币」；按网页文字提取核对', takeaway: '「赚币」已经是各家交易所的频道名，用了就等于和交易所站上同一个货架。', url: 'https://www.gate.com/zh/staking' },
  { group: 'cn', brand: 'Bitget（ETH 质押）', line: '质押以太坊，稳赚全网最高质押奖励 (ETH)', note: '页面主标题；同页还有「您的 以太坊 只增不减！」「100%保有本金」', takeaway: '「稳赚」「全网最高」「100%保有本金」「只增不减」都在我们的红线上，一个都不跟；「数量变多」这层意思只交给画面去表现。', url: 'https://www.bitget.com/zh-CN/price/ethereum/staking' },
  { group: 'cn', brand: 'HTX 火币（赚币）', line: '闲置数字资产增值服务', note: '页面描述（meta description），不是可见主标', takeaway: '把持有说成「闲置」、把质押说成「增值服务」，和长期持有者的自我认知冲突；我们写「没打算卖」「看好」，不写「闲置」。', url: 'https://www.htx.com/zh-cn/financial/earn' },
  { group: 'cn', brand: 'TokenPocket', line: '把质押资产的控制权归还给用户', note: '帮助中心教程正文，只针对其「自托管质押」方式', takeaway: '钱包竞品讲过控制权，但只在帮助文档里用技术口吻；我们把同一件事写成大白话的活动主题。', url: 'https://help.tokenpocket.pro/cn/faq/ethwallet/eth2.0/node-staking' },
  { group: 'cn', brand: 'Ledger（简体中文）', line: '安全质押您的 ETH 来赚取奖励*', note: '', takeaway: '国际钱包的中文页常见直译句式，主标还是「安全」「赚取」；中文写得地道，本身就是和它们的差异。', url: 'https://www.ledger.com/zh-hans/staking/%E4%BB%A5%E5%A4%AA%E5%9D%8A%E6%9D%83%E7%9B%8A%E8%B4%A8%E6%8A%BC' },
  { group: 'cn', brand: 'ethereum.org（以太坊官方中文）', line: '在保护以太坊的同时赚取奖励', note: '', takeaway: '官方讲的就是「两重意义」，印证老板的「为网络，也为你」；但官方把「为你」落在赚取奖励上，我们落在决定权上，也不用「在……的同时」这种句式。', url: 'https://ethereum.org/zh/staking/' },
  { group: 'cn', brand: 'Trust Wallet', line: '使用 Trust Wallet 赚取 Ethereum', note: '', takeaway: '国际钱包的中文页多是英文直译，自托管只是附带说明，主标仍是「赚」；钱包在中文市场还没有自己的质押语言。', url: 'https://trustwallet.com/zh-CN/staking/ethereum' },
  { group: 'global', brand: 'Lido', line: 'Stake Ether with Lido to get daily rewards while keeping full control of your staked tokens.', note: '页面描述（meta / 分享摘要），可见标题是 Stake Ether', takeaway: '英文市场把 rewards 和 control 并列已是标准写法，control 本身不新鲜；imToken 靠 Under Your Control 这句品牌话的一致性取胜。', url: 'https://stake.lido.fi/' },
  { group: 'global', brand: 'MetaMask（Earn 页）', line: 'Put your money to work for you.', note: '', takeaway: 'put to work 加 passive income 已经用滥，控制权只放在第三张卖点卡，还和 Withdraw anytime 绑在一起；我们把「工作」和私钥绑在一起，不承诺随时可取。', url: 'https://metamask.io/earn' },
  { group: 'global', brand: 'ether.fi', line: 'Earn rewards without putting your ETH on pause', note: '线上页面拦截访问，按 2026-08-19 的 Internet Archive 快照核对', takeaway: '竞品里少有的休眠隐喻（别让 ETH 暂停），但落点仍是 earn；「叫醒」在 ETH 质押品类里没人用过。', url: 'https://web.archive.org/web/20260819231424/https://www.ether.fi/stake' },
  { group: 'own', brand: 'imToken（十周年 CEO 公开信）', line: 'Stake，是让用户从持有者成为参与者。', note: '公开信正文里的一句，不是单独的口号', takeaway: '和片中「持有，也可以是参与」同源，是可以直接继承的自有品牌叙事，竞品没占。', url: 'https://support.token.im/hc/zh-cn/articles/58651141456921' },
  { group: 'own', brand: 'imToken（内容文章）', line: '不再只谈 APR：质押之后，你的 ETH 到底是谁的？', note: '文章标题', takeaway: '竞品主标没人讲归属，这篇已经开了题，可以升级成 PR 标题；但文中也写明 ETH 进入了存款合约，所以我们只讲归属，不讲位置。', url: 'https://support.token.im/hc/zh-cn/articles/61900756186137' },
  { group: 'own', brand: '蚂蚁金服', line: '每个认真生活的人，都值得被认真对待', note: '数英网的案例分析文章转引，不是蚂蚁官方页面', takeaway: '金融品牌不谈回报、谈尊重；老板说的「也为你」可以这样落在人身上：你多年的看好被认可。', url: 'https://www.digitaling.com/articles/19368.html' },
  { group: 'own', brand: 'BlockBeats 律动（媒体）', line: '9大远古巨鲸接连苏醒，这是最后一轮加密牛市吗？', note: '媒体新闻标题（2024-09），不是品牌宣传语', takeaway: '「沉睡巨鲸苏醒」是抛售新闻的固定句式；Bulu 是鲸鱼，PR 标题和社媒文案都不能把「鲸」和「醒」放在一起。', url: 'https://www.theblockbeats.info/news/55153' },
]

export const benchmarkGroups = { cn: '中文市场', global: '海外品牌', own: 'imToken 自己说过的话与参考' } as const

export const whitespace = '中文竞品的主标几乎都在讲利益和保障：交易所写「持币生息，安全无忧」「收益每天赚」「质押赚币」，把持有说成「闲置资产」，把质押归进理财货架；国际钱包的中文页多是英文直译，主标仍是「赚取」，控制权只放在副标、卖点卡或帮助文档里；英文市场的 rewards 加 control 已经成了默认写法。还没有人占住的位置有三个，而且都不碰回报承诺。第一，对长期持有者说话：认下「从买入那天起就没打算卖」这个选择，讲他熬过的时间，而不是每天赚多少。第二，把「私钥不交出去、不用先充进交易所」写成主题，这是交易所做不到、竞品又只在文档里提过的差异。第三，把老板的「为以太坊，也为你」写成一句地道中文，「为你」只落在决定权和信念被认可上。再加上 Bulu 和沉睡晶体这套拟人画面，「叫醒」可以成为 imToken 这次活动专属的动词。最后，写一手地道、干净的简体中文，本身就是和翻译腔竞品拉开距离的低成本差异。'

export const categories: TaglineCategory[] = [
  { key: 'wake', title: '叫醒与故事', en: 'Wake-up & Story', desc: '把全片「沉睡 → 醒来」写成一句话，靠故事和画面打动人；主口号、片尾、开场字幕和 Push 的主要来源。', color: '#007fff' },
  { key: 'holder', title: '写给长期持有者', en: 'For Long-term Holders', desc: '先认下「从买入那天起就没打算卖」这个选择，再给出一条路；不评价持有者，也不催他。', color: '#7c3aed' },
  { key: 'boss', title: '为以太坊，也为你', en: 'For Ethereum, and for You', desc: '从老板的「为网络工作，也为你工作」出发：一半写 ETH 为以太坊出力，一半写私钥、决定权和信念还在你这边，不写回报。', color: '#0d9488' },
  { key: 'control', title: '掌控与上线', en: 'Control & Launch', desc: 'imToken 最不可替代的差异：私钥不交出去，也不用先充进交易所；用于 PR 标题、Push、FAQ 和品牌签名行。', color: '#d97706' },
  { key: 'social', title: '社媒系列', en: 'Social Series', desc: '给 X、微博、小红书的短句和可以连载的格式，只用于社媒和 10/12–16 系列，不做 10/8 主口号。', color: '#db2777' },
  { key: 'ref', title: '同事提案 · 参考', en: 'Team Drafts (Reference)', desc: 'Mkt 同事原来的 5 个主题，原文照录，附可以保留的种子和需要注意的地方。', color: '#a0a5b7' },
]

export const taglines: Tagline[] = [
  {
    id: 'c01',
    category: 'wake',
    cn: '叫醒你的 ETH',
    en: 'Your ETH has slept long enough.',
    subCn: '继续持有，私钥也不交出去。用 imToken 质押',
    subEn: 'Stake it with imToken. Keep your keys.',
    idea: '整个活动的总主题，也是全片的那个动作：ETH 睡了好几年，现在把它叫醒。副标先回答持有者最关心的两件事：继续持有，私钥也不交出去。',
    fit: '和片尾「imToken 质押——叫醒你的 ETH」是同一句，KV 主标、片尾、社媒话题 #叫醒你的ETH 共用一句话。主标 6 个字，读一遍就记住。',
    risk: '币圈媒体常用「ETH 醒了」指价格启动，还有「沉睡巨鲸苏醒」这类抛售新闻，所以 KV 只配沉睡、醒来的晶体，不配 K 线；PR 标题不要把「鲸」和「醒」放在一句里。副标不写「不用卖」：太口语（Wilson 10/07），而且 Lido 路径如果是在 App 里兑换 stETH，技术上算一次卖出。',
    compliance: 'low',
    uses: ['主口号', 'KV', '片尾', '社媒', 'PR'],
    paths: 'both',
    tier: 'lean',
    boss: false,
    revisedFrom: '叫醒你的 ETH。',
    changeNote: '主标去掉句号（主标统一不加句末标点）；副标原来是「长期持有，也可以参与其中」，「其中」没有指代、像回译，改成持有者最关心的两件事，并用「私钥」代替「ETH 不交出去」，Lido 路径也成立。',
  },
  {
    id: 'c02',
    category: 'wake',
    cn: '行情看了几年，ETH 睡了几年',
    en: 'You watched the charts. Your ETH just slept.',
    subCn: '该叫醒它了。用 imToken 质押',
    subEn: 'Wake it up. Stake with imToken.',
    idea: '片子开头那一幕：Bulu 夜里盯着行情，ETH 在沙发另一头睡觉。两个「几年」前后呼应，一句话把人和币的状态都交代清楚。',
    fit: '视频开场字幕、PR 导语、社媒首句。11 个字，做 KV 主标偏长。',
    risk: '「ETH 睡了几年」离开画面时可能被读成「价格横盘几年」，配上 Bulu 和晶体就能拉回本意。不写「睡过牛熊」「穿越周期」。',
    compliance: 'low',
    uses: ['片内', 'PR', '社媒'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: '你醒着看行情，它睡着过周期。',
    changeNote: '删掉「过周期」，避开「穿越牛熊」的读法；后半句直接写 ETH，不再靠「它」；改成「看了几年 / 睡了几年」的同字呼应。',
  },
  {
    id: 'c03',
    category: 'wake',
    cn: '持有这么多年，该叫醒 ETH 了',
    en: 'Held for years. Time to wake up your ETH.',
    subCn: 'imToken 质押上线，私钥还在你手里',
    subEn: 'imToken Stake is live. Your keys stay with you.',
    idea: '把长期持有者的身份和「叫醒」放进一句话：拿了这么多年，是时候了。口吻是陪着他，不是催他。',
    fit: 'App Push 标题（13 字）、PR 标题、社媒长标题；副标是标准的上线句。',
    risk: 'PR 配图用晶体，不要单独用 Bulu 鲸鱼配「醒」字。社媒里可以换成更口语的「拿了这么多年」，KV 和 PR 用「持有」。',
    compliance: 'low',
    uses: ['Push', 'PR', '社媒'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: '从没卖过，从此醒着。',
    changeNote: '原句前后半句主语不一样，「从此醒着」容易被读成用户自己失眠、天天看盘；现在主语统一成持有者，ETH 做宾语，一看就知道醒的是 ETH。',
  },
  {
    id: 'c04',
    category: 'holder',
    cn: '不放手，也能质押',
    en: 'Stake without letting go.',
    subCn: '在 imToken 质押，私钥也不交出去',
    subEn: 'Stake with imToken and keep your keys.',
    idea: '「不放手」一句两层意思：从买入那天起就没卖，资产也没交给别人。长期持有者的坚持和 imToken 的非托管在这里重合，交易所说不出这句话。',
    fit: 'KV 第二行、App Push、片内 S09 光带出现那一刻的字幕备选。',
    risk: '「不放手」可能被读成随时能取回，后面不能接「随时赎回」「想取就取」，要配常驻风险提示。不要紧挨最后一屏「由你掌控」，意思会重复。',
    compliance: 'mid',
    uses: ['KV', 'Push', '片内', 'PR'],
    paths: 'both',
    tier: 'lean',
    boss: false,
    revisedFrom: '不放手，也能质押。',
    changeNote: '主标保留，去掉句号；副标「没放过手」改成「没松过手」，去掉「放过 = 饶过」的歧义；法律词「托管方」换成大家都懂的「私钥也不交出去」。',
  },
  {
    id: 'c05',
    category: 'holder',
    cn: '没打算卖，也不用干等',
    en: 'Not selling. Not just waiting.',
    subCn: '在 imToken 质押你的 ETH',
    subEn: 'Stake your ETH with imToken.',
    idea: '直接用核心用户心里那句「从买入那天起就没打算卖」，回答片中第一句旁白「持有，只能是等待吗？」：不卖，但也不只是等。',
    fit: 'KV、Push、社媒首图；和片子开头的旁白一问一答，适合 10/8 当天的社媒长图。',
    risk: '「干等」带一点自嘲，语气要靠画面放轻，不能写成「你一直在白等」。不用「站岗」「钻石手」这类圈内黑话。',
    compliance: 'low',
    uses: ['KV', 'Push', '社媒'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c06',
    category: 'holder',
    cn: '持有第 365 天，质押第 1 天',
    en: 'Day 365 of holding. Day 1 of staking.',
    subCn: '继续持有，今天开始在 imToken 质押',
    subEn: 'Keep holding. Start staking with imToken.',
    idea: '打卡体：两个「第几天」并排，一眼就懂，不用解释。用户可以把 365 换成自己的天数，做成 UGC 模板。',
    fit: '社媒系列、10/12–16 系列海报、UGC 互动（官方图用 365，评论区换成「第 N 天」）。365 和片中 S04 翻日历的 365 天对得上。',
    risk: '「第 1 天」只指发起质押那天，不要配「当天就有奖励」之类的话（质押激活要排队）。社媒里可以用更口语的「拿币」，KV 和 PR 用「持有」。',
    compliance: 'low',
    uses: ['社媒', '10/12 系列', 'Push'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: '持有第 N 天，质押第 1 天。',
    changeNote: 'N 改成 365，和片中的日历对上；副标不再解释这个梗，只留一句态度；去掉句号。',
  },
  {
    id: 'c07',
    category: 'boss',
    cn: '出力的是 ETH，做主的是你',
    en: 'Your ETH does the work. You call the shots.',
    subCn: '在 imToken 质押 ETH，私钥还在你手里',
    subEn: 'Stake with imToken. Support Ethereum, on your terms.',
    idea: '把老板说的「为网络工作，也为你工作」拆成两个角色：ETH 给以太坊出力，由你拿主意。「也为你」落在决定权上，不落在回报上。',
    fit: 'PR 标题、KV 副主题、老板视角的社媒长图。画面配容器和连着 Bulu 的光带；「为以太坊」这一半由画面和 PR 导语补上（导语可写：ETH 为以太坊出力，私钥还在你手里）。',
    risk: '「做主」指要不要质押、什么时候发起退出，不能延伸成「随时可取」。「出力」单独用，不写成公文腔的「出一份力」。「ETH 干活、你做主」的结构可能让人联想到「让钱替你打工」这类理财话术，Wilson 10/07 决定不放进当前倾向，只作备选。',
    compliance: 'mid',
    uses: ['PR', 'KV', '社媒'],
    paths: 'both',
    tier: 'alt',
    boss: true,
    revisedFrom: '为以太坊出力，由你做主。',
    changeNote: '原句没有主语，读者会以为是「你」在出力、在运行以太坊；改成「……的是 ETH，……的是你」，两个角色分清楚，政务口号的味道也没了；副标不再重复「出力」，补上私钥。',
  },
  {
    id: 'c08',
    category: 'boss',
    cn: '看好以太坊，不只是看着',
    en: 'Believe in Ethereum? Don\'t just watch.',
    subCn: '用 imToken 质押，让 ETH 为以太坊工作',
    subEn: 'Stake your ETH with imToken.',
    idea: '长期持有者其实是「看好以太坊的人」。「也为你」落在信念被认可上：你看好了这么多年，现在 ETH 真的在为以太坊工作。接上 CEO 公开信里的「从持有者成为参与者」。',
    fit: 'KV、PR 导语、X 和微博主帖。副标的「工作」和片中旁白用的是同一个动词。',
    risk: '「看着」带一点「光看不动」的意思，语气要轻，不能变成说教。「看好」在币圈也常指看涨，主标不要脱离副标单独使用。',
    compliance: 'low',
    uses: ['KV', 'PR', '社媒'],
    paths: 'both',
    tier: 'lean',
    boss: true,
    revisedFrom: '相信以太坊，就成为它的一部分。',
    changeNote: '「成为它的一部分」是 be part of it 的直译，还暗示用户自己在运行以太坊；改用「看好 / 看着」的同字呼应；副标不用「出一份力」，用片中已有的「工作」。',
  },
  {
    id: 'c09',
    category: 'boss',
    cn: '持有，也可以是参与',
    en: 'Holding can mean taking part.',
    subCn: '用 imToken 质押 ETH，私钥不用交出去',
    subEn: 'Stake your ETH with imToken. Your keys stay with you.',
    idea: '片中旁白原句。一句话里有两半：「持有」是资产还归你，「参与」是 ETH 在为以太坊出力。和 CEO 公开信「从持有者成为参与者」同源，是 imToken 已经公开说过的话。',
    fit: '片内旁白（已有）、PR 导语、社媒置顶。',
    risk: '「也可以是」虚词多，单独做 KV 主标偏软、像旁白，更适合和画面一起出现。「参与」不要延伸成「参与治理」或「运行以太坊」。',
    compliance: 'low',
    uses: ['片内', 'PR', '社媒'],
    paths: 'both',
    tier: 'keep',
    boss: true,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c10',
    category: 'boss',
    cn: 'ETH 去工作，钥匙在你手里',
    en: 'Your ETH goes to work. You keep the keys.',
    subCn: '在 imToken 质押，私钥不交出去',
    subEn: 'imToken Stake. Your keys stay with you.',
    idea: '把片中那条一直连着 Bulu 的光带说成一句大白话：ETH 去为以太坊工作，钥匙还在你手里。「为网络」和「为你」各占半句，「钥匙」暗合私钥。',
    fit: '视频 S09–S10 容器和光带出现时的字幕、社媒配图。',
    risk: '「去工作」容易让人联想到领工资，只配画面用，不进 PR 标题；「钥匙在你手里」不能延伸成「随时取回」。上一版的「线在你手里」已经改掉，因为风筝线会让人想到随时能拉回来。',
    compliance: 'mid',
    uses: ['片内', '社媒'],
    paths: 'both',
    tier: 'alt',
    boss: true,
    revisedFrom: '一头连着以太坊，一头连着你。',
    changeNote: '「一头连着……一头连着……」是新华体；改成具体的「钥匙」，主语写明是 ETH；英文 hold the line 是「坚守阵线」的固定说法，和光带对不上，改成 keep the keys。',
  },
  {
    id: 'c11',
    category: 'control',
    cn: '质押，由你掌控',
    en: 'Stake, Under Your Control',
    subCn: '打开 imToken，在钱包里质押 ETH',
    subEn: 'Stake ETH right from your imToken wallet.',
    idea: '直接沿用 imToken 十周年品牌主张「你的数字世界，由你掌控 / Your Digital World, Under Your Control」的句式，和最后一屏英文一一对应，不另造一句。',
    fit: '最后一屏的中文对应、KV 品牌签名行、10/19 Lido 活动的共同口径（两种质押方式都在自己的钱包里完成）。',
    risk: '品牌句很稳，但单看没有故事，适合做签名行，不适合单独做 10/8 的活动主标。英文沿用片尾的 Stake, Under Your Control（英文审稿建议过改成 Staking，Wilson 10/07：先不改）。',
    compliance: 'low',
    uses: ['片尾', 'KV', 'Lido 衔接'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c12',
    category: 'control',
    cn: '私钥不交出去，照样质押',
    en: 'Stake without handing over your keys.',
    subCn: '用 imToken，在自己的钱包里质押 ETH',
    subEn: 'Stake ETH with imToken. Your keys don\'t change hands.',
    idea: '把非托管翻成一句大白话：质押不等于把币交给别人。',
    fit: 'App Push 标题（11 字）、KV 副标、FAQ 标题。',
    risk: '「私钥」是术语，币圈用户都懂，圈外读者第一眼可能会卡一下；KV 上术语只留一个。「照样」后面不要接「随时」。',
    compliance: 'low',
    uses: ['Push', 'KV', 'PR'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c13',
    category: 'control',
    cn: '质押 ETH，不用先充进交易所',
    en: 'Stake ETH. No exchange deposit needed.',
    subCn: '打开 imToken 就能质押，私钥留在你手里',
    subEn: 'Stake right from your imToken wallet. Your keys stay with you.',
    idea: '不点名地讲清楚和交易所的差别：交易所要先把币充进去才能质押，imToken 不用。这是非托管最好懂的好处。',
    fit: 'PR 正文小标题、Push、社媒两格漫画（交易所质押 vs imToken 质押）。',
    risk: '带比较的意味，需要法务看一下比较广告的风险，不点交易所的名字。',
    compliance: 'mid',
    uses: ['PR', 'Push', '社媒'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c14',
    category: 'control',
    cn: '质押之后，资产仍归你',
    en: 'Your assets stay yours.',
    subCn: 'imToken 质押上线，在钱包里直接完成',
    subEn: 'imToken Stake is live, right in your wallet.',
    idea: '回答 imToken 9 月那篇文章自己提出的问题「质押之后，你的 ETH 到底是谁的？」：用归属来回答，不说 ETH 放在哪里。',
    fit: '10/8 垂直媒体 PR 标题、新闻稿首段。',
    risk: '用「资产」而不是「ETH」，因为 Lido 路径下用户拿到的是 stETH，「资产仍归你」两条路都成立。「仍归你」偏书面，放在 PR 合适，不放 KV。',
    compliance: 'mid',
    uses: ['PR'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c15',
    category: 'social',
    cn: 'Bulu 质押日记 · 第 1 天',
    en: 'Bulu\'s Staking Diary · Day 1',
    subCn: '我的 ETH 醒了，伸了个懒腰，开始工作。光带一直连着我',
    subEn: 'My ETH woke up, stretched, and got to work. Still linked to me.',
    idea: '角色日记系列：用 Bulu 的视角连载片中的画面，醒来、跳进容器、光带连着、Bulu 发呆。每条只写一个小动作。',
    fit: '10/12–16 系列内容，X 和小红书连载。',
    risk: '后面几天只写画面，不写 ETH 多了几颗，也不写奖励数字；「醒了」始终和「伸懒腰」这类动作连用，避免被读成价格启动；正文里不出现「鲸」字。日记用 Bulu 的第一人称；对外文案不出现「容器」这类制作用语。',
    compliance: 'low',
    uses: ['社媒', '10/12 系列'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c16',
    category: 'social',
    cn: '早安，ETH',
    en: 'GM, ETH.',
    subCn: '睡得够久了。打开 imToken，质押 ETH',
    subEn: 'That\'s enough sleep. Stake your ETH with imToken.',
    idea: '社媒早安栏目：每天早上发一张 Bulu 叫醒沙发上那颗晶体的图。中文用「早安」，GM 只用在英文和 X。',
    fit: '社媒系列开篇、早间 Push、X 英文帖。',
    risk: '「睡得够久了」单独看有点像训人，要靠 Bulu 拉开窗帘这类温和的画面把语气压住；不配 K 线。',
    compliance: 'low',
    uses: ['社媒', 'Push', '10/12 系列'],
    paths: 'both',
    tier: 'keep',
    boss: false,
    revisedFrom: 'GM，ETH。',
    changeNote: '中文里夹着 GM 读不出语气，圈外读者也不一定懂，中文版改成「早安」，GM 只留给英文版和 X。',
  },
  {
    id: 'c17',
    category: 'social',
    cn: '涨也是这一颗，跌也是这一颗',
    en: 'Up or down, same ETH.',
    subCn: '打开 imToken，叫醒这颗 ETH',
    subEn: 'Time to wake it up. Stake with imToken.',
    idea: '配 S04 牛熊段：晶体跟着行情变大变小、表情变来变去，但始终只有一颗。说的是长期持有者心里那句「拿了这么久，还是这么多」。',
    fit: '社媒表情包或动图（涨的表情、跌的表情）、S04 段配文。',
    risk: '只说「数量没变」，后面不能接「质押后就不怕跌」这类话；做主标时读者可能推出「质押后颗数会变多」，所以只放社媒、配画面，不进 KV、Push 和 PR。「一颗」是画面里的量词，不是持仓数字。',
    compliance: 'mid',
    uses: ['社媒', '片内'],
    paths: 'both',
    tier: 'alt',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c18',
    category: 'ref',
    cn: '',
    en: 'Your ETH Can Do More',
    subCn: '',
    subEn: 'Put idle ETH to work with imToken Stake',
    idea: '同事主题 1（原图只有英文）：把质押讲成让 ETH 多做点事。',
    fit: '可以保留的种子：work 这个动词，和片中旁白「也能工作」一致；idle 这个观察，片子已经把它升级成「沉睡」。',
    risk: 'Do more 是行业里常见的说法，单看不容易和其他质押服务区分开；idle 对应「闲置」，可能让长期持有者觉得自己多年的持有被说成闲置，这一版不沿用，换成「沉睡」会温和一些。',
    compliance: 'low',
    uses: ['KV', 'Push'],
    paths: 'both',
    tier: 'ref',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c19',
    category: 'ref',
    cn: '你钱包里的 ETH，其实可以质押。',
    en: 'The ETH in Your Wallet Can Stake.',
    subCn: '用 ETH，赚 ETH。',
    subEn: 'Earn ETH With Your ETH.',
    idea: '同事主题 2：用「钱包里」点出在自己的钱包里就能完成质押。',
    fit: '「钱包里」是五个主题里最贴近非托管差异点的说法，这一版的「私钥不交出去，照样质押」「质押 ETH，不用先充进交易所」都是从这颗种子长出来的。',
    risk: '「其实可以」偏告知，情绪弱一些；「赚 ETH / Earn ETH」属于法务提示过的收益表述，需要换掉；英文可以让人做主语，例如 Stake the ETH in your wallet。',
    compliance: 'high',
    uses: ['KV', 'Push'],
    paths: 'both',
    tier: 'ref',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c20',
    category: 'ref',
    cn: '发掘 ETH 的更多可能。',
    en: 'Make More of Your ETH.',
    subCn: '（原提案未附副标）',
    subEn: '(No subtitle in the original.)',
    idea: '同事主题 3：讲 ETH 还有更多可能。',
    fit: '和主题 1、4 是同一个方向，建议合并来看；「更多可能」这层意思，这一版由「叫醒你的 ETH」用更具体的动作和画面来表达。',
    risk: 'Make more 可能被读成 make more money，带一点收益暗示；「更多可能」适用面很广，和质押、长期持有的关系还不够具体；中英两句意思不完全对等。',
    compliance: 'mid',
    uses: ['KV'],
    paths: 'both',
    tier: 'ref',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c21',
    category: 'ref',
    cn: '发掘 ETH 的更多可能。',
    en: 'Do more with your ETH.',
    subCn: '（原提案未附副标）',
    subEn: '(No subtitle in the original.)',
    idea: '同事主题 4：和主题 1、3 同一个方向，中文与主题 3 相同（原文如此）。',
    fit: '和主题 1、3 合并来看；如果需要一句通用的品牌平台句，可以直接用「叫醒你的 ETH」。',
    risk: '英文 Do more 没有 make more 的收益联想，风险低于主题 3；中文「更多可能」和主题 3 相同，需要一起定稿。句子比较通用，没有点到长期持有者和非托管这两个重点。',
    compliance: 'low',
    uses: ['KV'],
    paths: 'both',
    tier: 'ref',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
  {
    id: 'c22',
    category: 'ref',
    cn: '别让你的 ETH 只是躺着。',
    en: 'Don\'t Let Your ETH Just Sit There.',
    subCn: '你的 ETH，也能复利。',
    subEn: 'Let Your ETH Compound.',
    idea: '同事主题 5：用「躺着」点出 ETH 一直没动，副标用复利讲增长。',
    fit: '「躺着」是五个主题里最接近「沉睡」的种子，片中已经升级成「你的 ETH，不必一直沉睡」和片尾的「叫醒你的 ETH」。',
    risk: '「别让」是祈使语气，可能有一点说教感，「躺着」也容易让人联想到「躺赚」；「复利」只适用于特定的质押方式，做标题容易被读成增长承诺，更适合放在功能说明里。',
    compliance: 'high',
    uses: ['KV', '片尾'],
    paths: 'native',
    tier: 'ref',
    boss: false,
    revisedFrom: '',
    changeNote: '',
  },
]

export const leaning = {
  summary: '以下仅供讨论，不是定稿。倾向三句分工：主口号用片尾已有的「叫醒你的 ETH」（C01），KV、片尾和话题共用一句；「不放手，也能质押」（C04）做 Push 和 KV 第二行，专讲非托管；老板视角用「看好以太坊，不只是看着」（C08），做 PR 标题和社媒长图，片中旁白「持有，也可以是参与」（C09）在片子里承担同一层意思。最后一屏的中文签名行用「质押，由你掌控」（C11）。',
  cardIds: ['c01', 'c04', 'c08'],
  questions: [
    'Wilson：10/8 主口号走故事线（C01 叫醒你的 ETH）还是老板视角（C08 看好以太坊，不只是看着）？还是三句分工，各用在不同物料上？',
    '法务：「做主」「不放手」「钥匙在你手里」会不会被读成随时可取？以太坊退出要排队，常驻风险提示怎么写才够？',
    '法务：C12–C14 不点名地和交易所对比（「不用先充进交易所」「资产仍归你」），有没有比较广告的风险？',
    '产品 + 法务：Lido 路径下用户拿到的是 stETH，「私钥不交出去」「资产仍归你」是否都成立？',
    '法务：幻想气泡段的配文边界，确认只写成幻想，不写「奖励够去旅行」这类受益者口吻。',
    'Wilson + Mkt：中文片尾「叫醒你的 ETH」和英文最后一屏 Stake, Under Your Control 意思不对等，中文要不要也补一屏「质押，由你掌控」？',
  ],
}

export const dropped: { cn: string; en: string; reason: string }[] = [
  { cn: '从信念，到共识。', en: 'From conviction to consensus.', reason: '「从 A，到 B」是企业年报和口号墙的写法，抽象、没有画面；「共识」在币圈多指撑价格的叙事，接近喊单。' },
  { cn: '你的耐心，也能以 ETH 计。', en: 'Your patience, now measured in ETH.', reason: '「以……计」是财报腔，整句读成「耐心能换来 ETH」，等于暗示回报。' },
  { cn: '不止于持有。', en: 'More than HODL.', reason: '「不止于」已经被用滥，任何质押服务都能说，还有一点「光持有不够」的说教感。' },
  { cn: '你守着它，它守护以太坊。', en: 'You hold it. It upholds Ethereum.', reason: '「守着」在币圈会读成被套硬扛，「守护」贴近安全承诺，主标还以「它」开头。' },
  { cn: '你的信念，在链上有分量。', en: 'Your conviction carries weight on-chain.', reason: '「有分量」配鲸鱼会读成大户才算数，原副标的「背书」接近担保，句式也像翻译。' },
  { cn: '这回，换你的 ETH 为以太坊站岗。', en: 'Now your ETH keeps watch over Ethereum.', reason: '「站岗」在币圈就是高位被套，全部物料禁用。' },
  { cn: 'ETH 住哪儿，就在哪儿质押。', en: 'Stake it where it lives.', reason: '放在交易所的 ETH 也适用，等于把差异点送给交易所；「哪儿」也偏北方口语。' },
  { cn: '它只认一个钱包：你的。', en: 'Loyal to one wallet. Yours.', reason: '冒号揭晓是英文写法，主标以「它」开头；原副标还暗示 ETH 已经离开钱包。' },
  { cn: '从你的钱包，直达以太坊。', en: 'Straight from your wallet to Ethereum.', reason: '「直达」像物流用语，描述的是 ETH 离开钱包的过程，和非托管主张打架。' },
  { cn: '私钥在你手里，质押也是。', en: 'Your keys. Your coins. Your stake.', reason: '「质押」是动作，不能「在手里」，搭配不通；私钥这层意思已由「私钥不交出去，照样质押」承接。' },
]

export const method = {
  rounds: [
    { no: 'R1', title: '第一轮 · 三个方向', note: '持有者情感、产品事实、品牌记忆度三个方向发散，加上同事的 5 个主题，按六项标准打分，筛出 5 条路线。' },
    { no: 'R2', title: '第二轮 · 双重价值视角', note: '加入「为网络工作，也为你工作」的视角，另有故事、产品、社媒三个方向；逐条做合规和中英审查后，和第一轮一起整理成 24 张卡。' },
    { no: 'R3', title: '中文修订版', note: '上一版中文有明显的翻译腔和公文腔。这一版先做线上调研（中文市场竞品、海外品牌、中文 Mkt 写法与币圈雷区），逐条诊断上一版，再中文先写、重新起稿 42 条，经中文创意总监、合规与英文两路审稿，最后由没参与过的中文终审和合规终审再审一遍，留下 17 条。' },
  ],
  criteria: ['说人话', '中文用户一眼能懂', '像专业 Mkt 写的', '跟着故事走', '合规', '中英各自地道'],
}

export const redLines = [
  '不说「赚 / 收益 / 生息 / 躺赚 / 被动收入」，不给任何比率，奖励只叫「质押奖励」',
  '不说「安全 / 保证 / 无风险」，不暗示随时可取',
  '不暗示 ETH 会被锁住：不写锁定、锁仓、冻结',
  '对外只说「imToken 质押」「质押你的 ETH」，不提原生质押和 32 ETH，不解释质押机制',
  '不暗示质押能对冲熊市，不写「穿越牛熊」',
  '不暗示用户自己在运行以太坊',
  '不用币圈负面黑话：站岗、韭菜、梭哈、躺、闲置、守着；PR 标题不把「鲸」和「醒」放在一起',
]
