// 宣传语提案 — app/projects/stake-video/taglines/page.tsx + components/StakeTaglines.tsx.
// Cards below are generated from the brainstorm output (bulu-stake-video docs/14 + round 2); edit text here directly if needed.

export type Tier = 'lean' | 'keep' | 'alt' | 'ref'
export type Risk = 'low' | 'mid' | 'high'
export type Paths = 'both' | 'native' | 'liquid' | 'n/a'

export interface TaglineCategory {
  key: string
  title: string
  en: string
  desc: string
  color: string
}

export interface Tagline {
  id: string
  category: string
  cn: string
  en: string
  subCn: string
  subEn: string
  idea: string
  fit: string
  risk: string
  compliance: Risk
  uses: string[]
  paths: Paths
  source: string
  tier: Tier
  boss: boolean
}

export const tierLabel: Record<Tier, string> = { lean: '当前倾向', keep: '值得保留', alt: '限定场景', ref: '参考' }
export const riskLabel: Record<Risk, string> = { low: '合规风险低', mid: '合规风险中', high: '合规风险高' }
export const pathLabel: Record<Paths, string> = { both: '原生 + Lido 都成立', native: '仅原生质押', liquid: '仅 Lido', 'n/a': '' }

export const stats = [
  { value: '24', label: '张提案卡，含同事提出的 5 个主题' },
  { value: '6', label: '类，按讲故事的角度分' },
  { value: '62', label: '条候选：两轮发散加同事主题' },
  { value: '6', label: '张卡体现「为网络工作，也为你工作」' },
]

export const bossLens = {
  reading: '我们理解老板的意思是：质押的 ETH 同时在做两份工作。一份为以太坊网络，作为验证者的保证金，为安全和共识背书；一份为持有者，协议奖励回到持有者自己的钱包控制之下。宣传语里我们把「也为你」落在归属不断开、决定权在你、多年的信念被看见这三处，不落在回报上。',
  guardrail: '「为你工作」不能写成让钱为你工作、躺赚、被动收入，不出现收益、回报和数字，也不能暗示用户自己在运行验证器或运行以太坊。老板原句的近义改写全图只保留 C10 一条。',
}

export const categories: TaglineCategory[] = [
  { key: 'wake-up', title: '叫醒与故事', en: 'Wake-up & Story', desc: '把全片「沉睡 → 醒来」写成一句话，靠故事和画面打动人；主口号、片尾和 KV 的主力来源。', color: '#007fff' },
  { key: 'holder', title: '持有者 · 信念与时间', en: 'Holder, Conviction & Time', desc: '先认下长期持有者的身份、信念和耐心，再讲质押的意义；偏 PR、KV 和 10/12–16 系列。', color: '#7c3aed' },
  { key: 'dual-value', title: '双重价值', en: 'Two Jobs, One ETH', desc: '从「为网络工作，也为你工作」出发：一半写 ETH 为以太坊出力，一半写归属、决定权或信念仍在你这边，不写回报。', color: '#0d9488' },
  { key: 'control', title: '非托管与控制权', en: 'Self-custody & Control', desc: 'imToken 最不可替代的差异点：在自己的钱包里质押，不交给托管方；适合第二行、Push 和10/12–16 系列。', color: '#d97706' },
  { key: 'social', title: '圈内语与社媒', en: 'Crypto-native & Social', desc: '给 X / 社区用的短句和可以天天更新的系列格式，靠圈内默契和二创传播，不做 10/8 主口号。', color: '#db2777' },
  { key: 'colleague', title: '同事提案 · 参考', en: 'Team Drafts (Reference)', desc: 'Mkt 同事提出的 5 个主题，原文照录（标「译」的是我们补的翻译），附可以保留的种子和需要注意的地方。', color: '#a0a5b7' },
]

export const taglines: Tagline[] = [
  {
    id: 'c01',
    category: 'wake-up',
    cn: '从没卖过，从此醒着。',
    en: 'Never sold. Now awake.',
    subCn: '信念不用改。在 imToken 质押，叫醒你的 ETH。',
    subEn: 'Same conviction. Wake up your ETH with imToken Stake.',
    idea: '先认下持有者「从没卖过」的身份，再写 ETH 的状态变化；「从没 / 从此」把全片沉睡到醒来压成 8 个字。',
    fit: '主口号首选候选：KV 主标、App Push 标题、PR 标题。对应 S01–S04 到 S09；与片尾 V12「叫醒你的 ETH」分工（这句说状态，V12 说动作）。不依赖质押路径，10/19 Lido 衔接可原句沿用。',
    risk: '不带非托管信息，差异点要靠第二行和片尾卡补；加密媒体常用「ETH 醒了」指价格启动，KV 只配晶体和容器，不配 K 线；「从没卖过」请法务看会不会被读成劝人别卖。',
    compliance: 'low',
    uses: ['主口号', 'KV', 'Push', 'PR', 'Lido 衔接'],
    paths: 'both',
    source: 'R1 评审提案',
    tier: 'lean',
    boss: false,
  },
  {
    id: 'c02',
    category: 'wake-up',
    cn: '叫醒你的 ETH。',
    en: 'Wake up your ETH.',
    subCn: '长期持有，也可以参与其中。',
    subEn: 'Keep holding. Start taking part.',
    idea: '全片的行动句（片中 V12）：既是邀请也是动作，一句话把观众带到「去 App 里质押」。',
    fit: '片尾 S12 的行动句（已在片中，不动）；Push 按钮 / CTA、社媒首帖配图字。与 C01 搭配时一条说状态、一条说动作。',
    risk: 'C01 的副标里已有「叫醒你的 ETH」，两者同屏要删掉一处；英文 wake up 也有「醒醒吧」的说教读法，语气靠画面兜；本身不带 imToken 差异点。',
    compliance: 'low',
    uses: ['片尾', '片内', 'Push', '社媒'],
    paths: 'both',
    source: 'R1 Claude 初稿',
    tier: 'keep',
    boss: false,
  },
  {
    id: 'c03',
    category: 'wake-up',
    cn: '你醒着看行情，它睡着过周期。',
    en: 'You watched every candle. Your ETH slept through every cycle.',
    subCn: '叫醒它，在 imToken 质押你的 ETH。',
    subEn: 'Wake it up. Stake your ETH with imToken.',
    idea: '醒着 / 睡着的镜像对仗：醒着的是深夜看行情的你，睡着的是 ETH；不责怪持有者，只写出那种停滞。',
    fit: 'KV 长版、PR 导语、社媒首帖；一一对应 S01–S04（深夜沙发、手机行情、毛毯上沉睡的 ETH、四季与牛熊），后接片尾「叫醒你的 ETH」。',
    risk: '太长，做不了 Push 和片尾卡；看盘意象可能被读成鼓励盯短线；candle 对圈外偏专业；和 C12「站岗」的开场镜像同源，两条只留一条。',
    compliance: 'low',
    uses: ['KV', 'PR', '社媒'],
    paths: 'both',
    source: 'R1 候选池',
    tier: 'alt',
    boss: false,
  },
  {
    id: 'c04',
    category: 'holder',
    cn: '相信以太坊，就成为它的一部分。',
    en: 'You believe in Ethereum. Now be part of it.',
    subCn: '在 imToken 质押你的 ETH，从看好以太坊，到参与以太坊。',
    subEn: 'Stake your ETH with imToken. Go from believing in it to taking part.',
    idea: '把质押从理财操作还原成信念的延伸：长期持有者买 ETH 是因为相信以太坊，质押让他从看好的人变成参与的人。',
    fit: '10/8 垂直媒体 PR 主标题、10/19 Lido 衔接；全句不提奖励，合规最干净。与片中 V11「持有，也可以是参与」同一论点，不再进片。与 C05、C11 同属信念方向，上会时三选一。',
    risk: '立意偏大，情绪落在理念而不是 Bulu 的故事；不含 imToken 差异点，任何质押服务商都能说；不能延伸成「你在运行以太坊」；中文 13 字，KV 要排两行。',
    compliance: 'low',
    uses: ['PR', 'Lido 衔接', 'KV', '10/12 系列'],
    paths: 'both',
    source: 'R1 评审提案',
    tier: 'keep',
    boss: false,
  },
  {
    id: 'c05',
    category: 'holder',
    cn: '从信念，到共识。',
    en: 'From conviction to consensus.',
    subCn: '你看好以太坊很多年了。在 imToken 质押你的 ETH，让它为你相信的网络出一份力。',
    subEn: 'You\'ve backed Ethereum for years. Stake your ETH with imToken and let it help secure the network you believe in.',
    idea: '「共识」一词两用：一层是持有者圈子里的共同信念（你），一层是以太坊的共识机制（网络）；质押就是把个人信念变成网络里实际出的一份力。',
    fit: 'KV 单行（6 字 / 4 词）、片尾前一屏、PR 标题、英文社媒；两条路径都成立，可原句跨到 10/19。比 C04 短得多，评审认为更好，但两条只能二选一（与 C04、C11 三选一）。',
    risk: '币圈说「共识」也常指支撑价格的叙事，可能被读成价格暗示，KV 只配脉动的晶体、不配 K 线；不带 imToken 差异点，靠副标和片尾卡补；大众读者未必读出共识机制这一层。',
    compliance: 'low',
    uses: ['KV', 'PR', '片内', '社媒', 'Lido 衔接'],
    paths: 'both',
    source: 'R2 产品真相',
    tier: 'keep',
    boss: true,
  },
  {
    id: 'c06',
    category: 'holder',
    cn: '你的耐心，也能以 ETH 计。',
    en: 'Your patience, now measured in ETH.',
    subCn: '一样的长期持有。这一次，协议奖励以 ETH 计，一点点累积。',
    subEn: 'Hold just as long. This time, protocol rewards accrue in ETH, little by little.',
    idea: '持有者投入最多的是时间和耐心，过去只能用法币价格衡量；这句把耐心换成币本位的刻度，用内行说法「以 ETH 计」讲质押的意义。',
    fit: 'KV、PR、10/12–16 系列；对上片子的视觉语法（质押前数量不变、计数器只显示增量），副标复用已审定的 V10b 措辞。V05、V10b 已在片中，不再进片。',
    risk: '五条提案里最接近奖励暗示：可能被读成耐心会换来 ETH，必须配常驻风险提示并请法务确认；英文 now measured 比中文「也能」更确定，法务可能要求改成 can be measured；Lido 路径下严格说是以 stETH 计。',
    compliance: 'mid',
    uses: ['KV', 'PR', '10/12 系列'],
    paths: 'both',
    source: 'R1 评审提案',
    tier: 'keep',
    boss: false,
  },
  {
    id: 'c07',
    category: 'holder',
    cn: '不止于持有。',
    en: 'More than HODL.',
    subCn: '你从未卖出的 ETH，也可以一起守护以太坊。',
    subEn: 'The ETH you never sold can help secure Ethereum.',
    idea: '承接 Mkt 物料里已有的 MORE THAN HODL 说法，把它当活动的平台句，副标补上「守护以太坊」这层意义。',
    fit: '英文 KV 品牌句、社媒；适合作为 C01 / C04 的英文上位句，沿用已有物料语汇，不需要新造。',
    risk: 'Mkt 物料里已在用，不算新提案；中文「不止于持有」偏通用，任何质押服务都能说；「不止于」可能被读成持有不够好；HODL 只用于英文版。',
    compliance: 'low',
    uses: ['KV', '社媒'],
    paths: 'both',
    source: 'R1 Claude 初稿',
    tier: 'alt',
    boss: false,
  },
  {
    id: 'c08',
    category: 'dual-value',
    cn: '一头连着以太坊，一头连着你。',
    en: 'Ethereum on one end. You on the other.',
    subCn: '在 imToken 质押你的 ETH：它为以太坊的共识出一份力，另一头仍连着你自己的钱包。',
    subEn: 'Stake your ETH with imToken. It helps secure Ethereum, while the other end stays connected to your own wallet.',
    idea: '把片中「光带连着 Bulu、不能断开」写成一句话，并给光带补上另一端：一端是网络（为以太坊出力），一端是你（归属不断开），正好是两份工作。',
    fit: '第二行候选（与 C13 二选一，不同屏）：KV（画出光带两端）、片尾卡前一屏、PR、社媒；原生和 Lido 两条路径都成立。不能紧挨片尾 Under Your Control。',
    risk: '「一头…一头…」是新华体高频句式，Mkt 要判断会不会显得公文腔；片中光带目前只连着 Bulu，网络那一端需要 KV 和后期补画面，否则只兑现一半；副标在 Lido 下指 stETH 在你钱包，请法务确认；中文 12 字，KV 排两行。',
    compliance: 'low',
    uses: ['KV', '片内', 'PR', '社媒', 'Lido 衔接'],
    paths: 'both',
    source: 'R2 老板视角',
    tier: 'lean',
    boss: true,
  },
  {
    id: 'c09',
    category: 'dual-value',
    cn: '你守着它，它守护以太坊。',
    en: 'You hold it. It upholds Ethereum.',
    subCn: '这些年，你一直守着它。现在，在 imToken 质押你的 ETH，让它为以太坊的安全出一份力。',
    subEn: 'For years, you\'ve kept it close. Now stake it with imToken, and let it help secure Ethereum.',
    idea: '一个「守」字两用：你守着 ETH（持有、自托管），ETH 守护以太坊（为网络安全作保）；先认下持有者的坚持，再把同一个动词交给 ETH。英文用 hold / uphold 做英语自己的双关。',
    fit: '主口号的老板视角竞争者，也可替代 C04 做 PR 标题；KV 单行（10 字 / 6 词）、Push。前半句接 S01–S04，后半句接 S09–S10，一句把片子前后两半接起来。',
    risk: 'uphold 把单个用户的 ETH 说成撑起整个网络，法务可能要求改成 helps uphold；「守护」只指网络，不能被读成对用户资产的安全承诺；主标交易所也能说，差异点靠片尾卡补（副标已去掉「由你掌控」，避免抢最后一屏的母题）；Lido 下「它」要理解成质押仓位。',
    compliance: 'low',
    uses: ['主口号', 'KV', 'PR', 'Push', 'Lido 衔接'],
    paths: 'both',
    source: 'R2 产品真相',
    tier: 'lean',
    boss: true,
  },
  {
    id: 'c10',
    category: 'dual-value',
    cn: '为以太坊出力，由你做主。',
    en: 'Works for Ethereum. Answers to you.',
    subCn: '在 imToken 质押你的 ETH：它为以太坊的安全出一份力，拿主意的仍然是你。',
    subEn: 'Stake your ETH with imToken. It helps secure Ethereum, and the decisions stay with you.',
    idea: '本图唯一一条贴近老板原句的对句：前半「为网络工作」保留，后半把「为你工作」换成「由你做主 / answers to you」，从替你挣钱转成听你的。合并自 R2「故事与角色」和「产品真相」两条同英文候选，副标取后者。',
    fit: 'KV、Push、英文社媒；放在片尾卡之前的物料上，不紧挨片尾 Under Your Control。英文 answers to you 是地道的职场说法，读起来像原创。',
    risk: '离老板原句最近，可能被认为只是同义改写；「做主」可能被读成随时可取，需常驻风险提示；只能指用户对自己仓位的决定，不能延伸成用户在指挥验证器；Works for 仍带一点让 ETH 工作的品类腔。法务若否掉「做主」，评审给的备选是「你签名，它出力 / You sign. It serves Ethereum.」，但「签名」也是验证者的术语，需一起评估。',
    compliance: 'mid',
    uses: ['KV', 'Push', '社媒'],
    paths: 'both',
    source: 'R2 故事与角色',
    tier: 'keep',
    boss: true,
  },
  {
    id: 'c11',
    category: 'dual-value',
    cn: '你的信念，在链上有分量。',
    en: 'Your conviction carries weight on-chain.',
    subCn: '在 imToken 质押你的 ETH，让它为以太坊的安全与共识背书。',
    subEn: 'Stake your ETH with imToken and let it stand behind Ethereum\'s security and consensus.',
    idea: '「分量」一词两用：对网络，是质押的 ETH 在共识里的权重（stake weight）；对你，是多年信念终于被算进去、被看见。',
    fit: 'KV（配晶体亮起、开始脉动的画面）、PR、英文社媒；对应 S09 ETH 醒来、S10 计数器起跳前那一刻。两条路径都成立。与 C04、C05 同属信念方向，三选一。',
    risk: '对圈外读者偏抽象，必须有画面撑着；「分量」不能延伸成治理投票权；修改版已把奖励从副标拿掉，避免托管味和费用口径问题；英文多了 on-chain 才和中文对等。',
    compliance: 'mid',
    uses: ['KV', 'PR', '社媒'],
    paths: 'both',
    source: 'R2 故事与角色',
    tier: 'alt',
    boss: true,
  },
  {
    id: 'c12',
    category: 'dual-value',
    cn: '这回，换你的 ETH 为以太坊站岗。',
    en: 'Now your ETH keeps watch over Ethereum.',
    subCn: '这些年，一直是你守着它。在 imToken 质押你的 ETH，让它为你相信的以太坊出一份力。',
    subEn: 'For years, you kept watch over it. Stake your ETH with imToken, and let it help secure the Ethereum you believe in.',
    idea: '守夜交班：开场是 Bulu 醒着、ETH 在毯子上睡；质押后换 ETH 醒着为网络站岗。「为你」落在守护你相信的那个网络，不落在资产，也不落在回报。',
    fit: '片尾卡前一屏、PR 导语、KV（拆两行：这回，换你的 ETH / 为以太坊站岗）；接 S01–S03 和 S09。与 C09 同属守护母题，二选一。',
    risk: '「站岗」若被读成替你守住资产就成了安全承诺，KV 上不能写守护你的 ETH；「在岗」暗示不间断运行，验证器离线或被罚没时说不通；已去掉「夜」字（守灵、看盘联想）；主标偏长，英文离开画面偏抽象，最好和副标第一句一起出现。',
    compliance: 'mid',
    uses: ['片内', 'PR', 'KV'],
    paths: 'both',
    source: 'R2 老板视角',
    tier: 'alt',
    boss: true,
  },
  {
    id: 'c13',
    category: 'control',
    cn: '不放手，也能质押。',
    en: 'Stake without letting go.',
    subCn: '从买入那天起，你就没放过手。在 imToken 质押，也不必把 ETH 交给任何托管方。',
    subEn: 'You\'ve held since day one. With imToken, staking doesn\'t mean handing it over.',
    idea: '「不放手」双关：一层是 HODL 的不卖，一层是非托管的不交出控制权。交易所质押第一步就是把币充进去，所以这句只有自托管钱包能说。',
    fit: '第二行首选候选（与 C08 二选一）：KV 副标、App Push 正文；片内可作为 V09 的备选，落在 S09 光带出现的那一刻。所有权这一组里只有它跨到 10/19 不用改写。不要和最后一屏连着出现。',
    risk: '「不放手」可能被读成随时可取，而两条路径都有退出等待期，必须有风险提示兜底；Lido 路径下 ETH 进入 Lido 合约，「不交给托管方」请法务确认；中文偏口语，单独上 KV 要靠光带画面或副标。',
    compliance: 'mid',
    uses: ['KV', 'Push', '片内', 'Lido 衔接'],
    paths: 'both',
    source: 'R1 评审提案',
    tier: 'lean',
    boss: false,
  },
  {
    id: 'c14',
    category: 'control',
    cn: 'ETH 住哪儿，就在哪儿质押。',
    en: 'Stake it where it lives.',
    subCn: '它在你的钱包里住了这些年。现在，就在 imToken 里质押。',
    subEn: 'It\'s lived in your wallet for years. Now stake it right there, with imToken.',
    idea: '把非托管翻译成「不用搬家」：钱包是 ETH 的家，质押就在家里发起。延续同事主题 2 唯一被保留的「钱包里」锚点，加上陪伴多年的品牌信任。',
    fit: 'Push 标题、KV；可作为 C13 的替代第二行（没有随时可取的歧义，也不用「托管方」这类需法务确认的词）。片中 ETH 一直住在 Bulu 家、容器也在客厅里，画面成立。不进片，避免和 V09 重复。',
    risk: '和片中 V09「ETH 不离开你的钱包，也能工作」是同一主张，口径随 V09 的法务结论；ETH 实际进入存款合约或 Lido 合约，「住」只能比喻控制权；副标默认老用户，拉新渠道要改写。',
    compliance: 'mid',
    uses: ['Push', 'KV', 'Lido 衔接'],
    paths: 'both',
    source: 'R2 产品真相',
    tier: 'keep',
    boss: false,
  },
  {
    id: 'c15',
    category: 'control',
    cn: '它只认一个钱包：你的。',
    en: 'Loyal to one wallet. Yours.',
    subCn: '在 imToken 质押你的 ETH，它记得自己是从谁的钱包出发的。',
    subEn: 'Stake your ETH with imToken. It never forgets whose wallet it came from.',
    idea: '把提款地址指向用户钱包这个最硬、也最枯燥的非托管事实拟人化：片中会打呼噜、会蹦跳的 ETH，像宠物一样只认主人。',
    fit: '10/12–16 系列、Push、社媒；光带「不能断开」的规则就是这句话的画面版。文案里不写「原生」，靠投放节点限定。',
    risk: '只在原生路径成立（Lido 下要改成 stETH 在你钱包），不能做主口号；需产品确认提款凭证是否一律指向用户地址且不可改；「只认」是绝对化表述；副标已去掉原稿的退出口径（有锁仓暗示）；拟人放在严肃 PR 里偏轻。',
    compliance: 'mid',
    uses: ['10/12 系列', 'Push', '社媒'],
    paths: 'native',
    source: 'R1 候选池',
    tier: 'alt',
    boss: false,
  },
  {
    id: 'c16',
    category: 'control',
    cn: '从你的钱包，直达以太坊。',
    en: 'Straight from your wallet to Ethereum.',
    subCn: '在 imToken 质押你的 ETH：从你自己的钱包出发，中间不经过任何托管方。',
    subEn: 'Stake your ETH with imToken, straight from your own wallet, with no custodian in between.',
    idea: '讲原生质押的直接性：钱包到以太坊之间没有托管层。对懂行的用户，「直达协议」本身就代表专业和可信，不需要用「安全」这类词。',
    fit: '10/8 垂直媒体 PR 小标题、10/12–16 系列；和光带从手机连到容器、中间没有第三方的画面对应。',
    risk: 'Lido 路径要经过 Lido 合约，和 10/19 矛盾，只适合原生阶段；「直达」可能淡化基础设施服务商和服务费，需在 FAQ 说明运维方角色；「不经过任何托管方」请法务确认。',
    compliance: 'mid',
    uses: ['PR', '10/12 系列'],
    paths: 'native',
    source: 'R1 候选池',
    tier: 'alt',
    boss: false,
  },
  {
    id: 'c17',
    category: 'social',
    cn: 'GM，ETH。',
    en: 'GM, ETH.',
    subCn: '睡得够久了。在 imToken 质押你的 ETH。',
    subEn: 'It\'s slept long enough. Stake it with imToken.',
    idea: '借加密圈每天互道的 GM，向沉睡的 ETH 说早安，把「叫醒」换成圈内暗号，做成可以天天更新的社媒系列。',
    fit: '社媒首帖、X 话题、S09 ETH 醒来时的字卡；10/19 可延展成 GM, stETH.。大众中文渠道用「早安，ETH。」兜底。只做社媒系列，不做 10/8 主口号。',
    risk: '大众中文用户和垂直媒体编辑未必认识 GM，语气偏玩梗；GM 人人都在说，品牌独占性弱，必须配 Bulu 和晶体视觉；不带非托管信息；Push 只写 GM 打开率难测。',
    compliance: 'low',
    uses: ['社媒', '片内', 'Lido 衔接'],
    paths: 'both',
    source: 'R1 评审提案',
    tier: 'keep',
    boss: false,
  },
  {
    id: 'c18',
    category: 'social',
    cn: '持有第 N 天，质押第 1 天。',
    en: 'HODL: day N. Staking: day 1.',
    subCn: '持有的天数照常往上数，质押从今天数起。在 imToken 质押你的 ETH。',
    subEn: 'Still holding. Now staking too. Stake your ETH with imToken.',
    idea: '日志体双计数（例：持有第 2190 天，质押第 1 天）：先让持有者晒出最骄傲的持有天数，再把质押当新的第一天；两个计数同时往上走，表达质押后仍在持有。',
    fit: '社媒系列：官方号每天更新 Bulu 的两个计数，用户晒自己的天数参与（UGC，话题如 #Day1Staking）；可延伸到10/12–16 系列。对应 S04 日历翻页和 S08 开始质押。Push 用短版，如「持有六年，质押第一天」。',
    risk: '不是独立主标（N 要填数字），不做主口号、KV、PR 标题；不做读取用户真实持有天数的个性化 Push（隐私与信任）；UGC 只晒天数，提示不晒地址和余额；原生有激活排队，「质押第 1 天」不等于当天开始产生奖励；年数以 S04 台历定稿为准；不能写成持有越久越该质押。',
    compliance: 'low',
    uses: ['社媒', '10/12 系列', 'Push'],
    paths: 'both',
    source: 'R2 社媒短句',
    tier: 'keep',
    boss: false,
  },
  {
    id: 'c19',
    category: 'social',
    cn: '私钥在你手里，质押也是。',
    en: 'Your keys. Your coins. Your stake.',
    subCn: '从持有到质押，自托管一路不断线。',
    subEn: 'Self-custody doesn\'t stop where staking starts.',
    idea: '把圈内最熟的 Not your keys, not your coins 续写到质押；交易所说不了这句话，天然区分自托管和交易所质押。',
    fit: '英文圈内社媒、可做 C13 的英文圈内变体；不做大众渠道和 Push。',
    risk: '这里的私钥只能指钱包私钥，原生路径的验证器签名密钥在服务商处，技术型用户会挑刺，FAQ 要分开讲；句式被硬件钱包和社区用得很多，独占性弱；Your stake 也有股权、权益的读法；中英结构不对等。',
    compliance: 'mid',
    uses: ['社媒'],
    paths: 'both',
    source: 'R1 候选池',
    tier: 'alt',
    boss: false,
  },
  {
    id: 'c20',
    category: 'colleague',
    cn: '你的 ETH，还能做更多（译）',
    en: 'Your ETH Can Do More',
    subCn: '用 imToken Stake，让闲置的 ETH 动起来（译）',
    subEn: 'Put idle ETH to work with imToken Stake',
    idea: '同事主题 1（原图只有英文）：把质押讲成让闲置的 ETH 多做点事。',
    fit: '原定 10/8 主传播、KV 与 Push 标题。可保留的种子：work 这个动词（与 V09「也能工作」一致）、idle 的观察（片子已升级成「沉睡」）。',
    risk: 'Do more 是行业里常见的说法，单看这一句不容易和其他质押服务区分开；idle 可能让长期持有者觉得被说成「闲着」。',
    compliance: 'low',
    uses: ['主口号', 'KV', 'Push'],
    paths: 'both',
    source: '同事提案',
    tier: 'ref',
    boss: false,
  },
  {
    id: 'c21',
    category: 'colleague',
    cn: '你钱包里的 ETH，其实可以质押。',
    en: 'The ETH in Your Wallet Can Stake.',
    subCn: '用 ETH，赚 ETH。',
    subEn: 'Earn ETH With Your ETH.',
    idea: 'Mkt 备选标题：用「钱包里」点出 ETH 不用转走就能质押。',
    fit: '原为 KV / Push 备选标题。「钱包里」是五条里唯一贴近非托管差异点的说法，已被 C14「ETH 住哪儿，就在哪儿质押」继承。',
    risk: '「其实可以」偏告知，情绪弱一些；「赚 ETH / Earn ETH」属于法务提示过的收益承诺表述，需要换掉；英文建议让人做主语：Stake the ETH in your wallet 或 Stake right from your wallet。',
    compliance: 'high',
    uses: ['KV', 'Push'],
    paths: 'both',
    source: '同事提案',
    tier: 'ref',
    boss: false,
  },
  {
    id: 'c22',
    category: 'colleague',
    cn: '发掘 ETH 的更多可能',
    en: 'Make More of Your ETH',
    subCn: '（原提案未附副标）',
    subEn: '(No subtitle in the original.)',
    idea: '同事主题 3（原图英文主标 + 中文一行）：讲 ETH 还有更多可能。',
    fit: '原为 KV 标题候选；和主题 1、4 是同一个方向，建议合并来看。',
    risk: 'Make more 有被读成 make more money 的可能，带一点收益暗示；「更多可能」适用面很广，和质押的关联不够具体；中英两句意思不完全对等。',
    compliance: 'mid',
    uses: ['KV'],
    paths: 'both',
    source: '同事提案',
    tier: 'ref',
    boss: false,
  },
  {
    id: 'c23',
    category: 'colleague',
    cn: '发掘 ETH 的更多可能',
    en: 'Do more with your ETH',
    subCn: '（原提案未附副标）',
    subEn: '(No subtitle in the original.)',
    idea: '同事主题 4（原图英文主标 + 中文一行）：与主题 1、3 同一方向，中文与主题 3 相同（原文如此）。',
    fit: '原为 KV 标题候选；和主题 1、3 是同一个方向，建议合并来看。',
    risk: '合规上问题不大；句子比较通用，没有点到长期持有者和非托管这两个重点；和主题 3 共用一句中文。',
    compliance: 'low',
    uses: ['KV'],
    paths: 'both',
    source: '同事提案',
    tier: 'ref',
    boss: false,
  },
  {
    id: 'c24',
    category: 'colleague',
    cn: '别让你的 ETH 只是躺着。',
    en: 'Don\'t Let Your ETH Just Sit There.',
    subCn: '你的 ETH，也能复利。',
    subEn: 'Let Your ETH Compound.',
    idea: '同事主题 5：用「躺着」点出 ETH 在闲置，副标用复利讲增长。',
    fit: '原为 KV / 片尾备选。「躺着」是这组里最接近沉睡意象的种子，已升级成片中的「你的 ETH，不必一直沉睡」。',
    risk: '「别让」是祈使语气，可能有一点说教感；「复利」只适用于特定的质押方式，做标题时容易被读成增长承诺，更适合放在功能说明里。',
    compliance: 'high',
    uses: ['KV', '片尾'],
    paths: 'native',
    source: '同事提案',
    tier: 'ref',
    boss: false,
  },
]

export const leaning = {
  summary: '以下仅供讨论，不是定稿。当前倾向是「一句主口号 + 一句第二行」的组合：主口号用 C01「从没卖过，从此醒着 / Never sold. Now awake.」，它跟着故事走、两条路径都成立；第二行在 C13「不放手，也能质押」（只讲非托管，最短）和 C08「一头连着以太坊，一头连着你」（同时写出网络和你两端，最贴老板的双重价值理解）之间二选一，两条不同屏。C09「你守着它，它守护以太坊」是老板视角里最干净的一条，可以和 C01 竞争主口号，或替代 C04 做 10/8 PR 标题。最后一屏 Stake, Under Your Control 不动，C08、C10 都不能紧挨它。',
  cardIds: ['c01', 'c13', 'c08', 'c09'],
  questions: [
    'Wilson：主口号走故事线（C01 从没卖过，从此醒着）还是老板视角（C09 你守着它，它守护以太坊）？第二行用 C13「不放手」还是 C08「一头连着」？信念方向 C04 / C05 / C11 留哪一条？',
    '法务：「不放手 / 由你做主 / 另一头仍连着你自己的钱包」会不会被读成随时可取？两条路径都有退出等待期，常驻风险提示怎么写才够？',
    '法务：「守护 / 站岗 / 为以太坊的安全出一份力」会不会被读成对用户资产的安全承诺？uphold 是否需要弱化为 helps uphold？',
    '法务 + 产品：Lido 路径下用户持有的是 stETH，「你的 ETH」「连着你的钱包」「不交给托管方」这些说法是否成立？原生质押的提款凭证是否一律指向用户钱包且不可修改（C08、C15 依赖）？',
    'Wilson + Mkt：采用 C08 的话，光带「以太坊那一端」是否在 KV 和后期补一个网络端的视觉？中文「一头……一头……」会不会显得公文腔？老板是否认同把「也为你」落在归属和信念上，而不是奖励上？',
  ],
}

export const dropped: { cn: string; en: string; reason: string }[] = [
  { cn: '奖励，也不离场。', en: 'Rewards that stay staked.', reason: '「不离场 / stay staked」有被读成奖励取不出、被锁住的风险，和 10/06 定下的「不暗示锁住」口径冲突；副标还在讲复利模式和验证器的机制细节。' },
  { cn: '坚定持有，不等于原地等待。', en: 'HODL isn\'t a waiting game.', reason: '和片中旁白 V06「持有，只能是等待吗？」、V11「持有，也可以是参与」重复。' },
  { cn: '还是你的 ETH，只是醒了。', en: 'Still yours. Now awake.', reason: '醒来的钩子由 C01 承担，所有权这半在 Lido 路径下字面不成立（用户拿的是 stETH）。' },
  { cn: '你的耐心，从此以 ETH 计。', en: 'Your patience, now measured in ETH.', reason: '已打磨成提案版 C06（「从此」改成「也能」）。' },
  { cn: '给你从没想过卖的那份 ETH。', en: 'For the ETH you\'ll never sell.', reason: '和 C01 是同一个「从没卖过」钩子，中文做标题偏弱，never sell 还有投资建议的读法。' },
  { cn: '质押了，还是你的。', en: 'Staked. Still yours.', reason: '说的是资产状态，Lido 的 stETH 和验证器密钥场景容易被挑刺；所有权状态这一组只留 C15 做10/12–16 系列代表。' },
  { cn: '从没卖过，从此醒着。（候选池原版）', en: 'Never Sold. Now Awake.', reason: '已打磨成提案版 C01。' },
  { cn: '你在等 ETH，ETH 也在等你。', en: 'Waiting on your ETH? It\'s waiting on you.', reason: '有 FOMO 催促感，并且和 C06 都在讲时间。' },
  { cn: '持有以太坊，也参与以太坊。', en: 'Don\'t just hold Ethereum. Help run it.', reason: 'Help run it 容易和独立质押混淆（暗示用户在运行以太坊），参与的意思已并入 C04。' },
  { cn: '无论牛熊，ETH 在岗。', en: 'Bull or bear. On duty.', reason: '容易被读成熊市也有回报、质押能对冲下跌，命中牛熊红线。' },
  { cn: 'GM，ETH。（候选池原版）', en: 'GM, ETH.', reason: '已打磨成提案版 C17。' },
  { cn: '不放手，也能质押。（候选池原版）', en: 'Stake without letting go.', reason: '已打磨成提案版 C13。' },
  { cn: 'ETH 可以变多，主人不会换。', en: 'Your stack can grow. Its owner never changes.', reason: '「可以变多」有奖励暗示，所有权状态这一组只留 C15。' },
  { cn: '质押，不必放手。', en: 'Stake without letting go.', reason: '和 C13 同一钩子，原副标还提了「原生」。' },
  { cn: '让持有的每一天都算数。', en: 'Make every day of HODL count.', reason: '和 C06 同为时间钩子，「算数」有每天都有回报的读法，副标还依赖复利机制。' },
  { cn: '让 ETH 醒着，你可以安心睡。', en: 'Your ETH stays awake. So you can rest.', reason: '「安心」接近绝对化承诺，也有躺平的读法；交班意象已由 C12 承接。' },
  { cn: '你守着 ETH，它守着以太坊。', en: 'Guarded by you. Now guarding Ethereum.', reason: '和 C09 是同一个「守」双关，C09 合规更干净、英文更利落；「依然在你身边」脱离画面不成立。' },
  { cn: '它为以太坊效力，由你做主。', en: 'Works for Ethereum. Answers to you.', reason: '和 C10 英文相同，已合并，副标取这一版。' },
  { cn: '一颗 ETH，身兼两职。', en: 'One ETH. Double duty.', reason: '「一颗 ETH」是数量表述且原生有门槛，Double duty 读成双倍，第二份差事会被补成替你赚钱。' },
  { cn: '为以太坊出力，记在你名下。', en: 'Backing Ethereum. In your name.', reason: '交易所账户同样记在你名下，差异点不成立，in your name 还有代你操作的托管味。' },
  { cn: '给以太坊上班，老板还是你。', en: 'New job: Ethereum. Same boss: you.', reason: '「老板还是你」就是让钱为你打工的换说法，还暗示你在指挥验证工作。' },
  { cn: '你的 ETH，开始居家办公。', en: 'Your ETH now works from home. / WFW: Work From Wallet.', reason: '三个视角各出了一次；home 撞以太坊术语 home staking（独立质押），上班也是理财话术。' },
  { cn: '以太坊，有你一份。', en: 'Your stake in Ethereum.', reason: '中文读成分一杯羹，英文 stake in 是股权读法，带证券化联想。' },
  { cn: '权益证明，也是信念证明。', en: 'Proof of stake. Proof of conviction.', reason: 'Proof of Conviction 已被预售项目使用，信念证明还暗示不质押就不算真信徒。' },
  { cn: '大家的以太坊，你的 ETH。', en: 'Everyone\'s Ethereum. Your ETH.', reason: '没有动词也没提质押，任何钱包都能用，圈外读者分不清 Ethereum 和 ETH。' },
  { cn: '你和以太坊，双向奔赴。', en: 'You and Ethereum. Now it\'s mutual.', reason: '互惠框架是隐性回报承诺，网络热词也已显旧。' },
  { cn: '你的 ETH，醒着的第一年。', en: 'Your ETH\'s first year awake.', reason: '「第一年」有锁定期暗示，配 S10 计数器等于给出年化数字，上线当天也不成立。' },
  { cn: '你的 ETH，和你一样不急。', en: 'Your ETH, patient like you.', reason: '「不急」会被读成取出要等很久、被锁住，也没写出沉睡到醒来的变化。' },
  { cn: '答案，一直在你的钱包里。', en: 'In your wallet all along.', reason: '离开 V06 问句不能单独成立，中英不对等，还有钱包里藏着可挖价值的联想。' },
  { cn: '持有，第二章。', en: 'HODL, Chapter Two.', reason: '没有质押、没有 imToken、离开画面读不懂；章节结构可留给系列视频编号。' },
  { cn: '原来，持有可以是这种感觉。', en: 'So this is how holding feels.', reason: '落在 S12 时「这种感觉」指向看到 ETH 变多，构成隐性收益暗示，且是通用广告模板。' },
  { cn: '为以太坊出力，以你的名义。', en: 'For Ethereum. In your name.', reason: '「以你的名义」在金融语境常见于防冒名提示，in your name 本义是代你办，与非托管相反。' },
  { cn: '它在工作，就在你眼前。', en: 'At work. In plain sight.', reason: '英文像 hiding in plain sight，「看得见」易滑向收益看得见，还有比较广告风险。' },
  { cn: '你的 ETH，也与以太坊同频。', en: 'Your ETH, in step with Ethereum.', reason: '太抽象，可能被读成跟着价格同涨跌，与 C05 同一意义线但更弱。' },
  { cn: '你签名，它出力。', en: 'You sign. It serves.', reason: 'It serves 没有宾语，「签名」是机制词；仅作为 C10 被法务否掉时的备选记在 C10 风险里。' },
  { cn: '你的 ETH，身兼两职。', en: 'Your ETH, on double duty.', reason: '两职 / double 扫读即双份收益，副标还把一颗 ETH 拆成两份，违背视觉语法。' },
  { cn: '为以太坊干活，由你签名。', en: 'Works for Ethereum. Signed by you.', reason: '「签名」在以太坊里正是验证者的日常工作，连读等于说你在运行验证器。' },
  { cn: '你的信念，以太坊看得见。', en: 'Proof of Conviction.', reason: '中英不对等，主副标连读等于有信念就有回报；Proof of Conviction 只能做英文话题标签。' },
  { cn: '质押，不追着数字跑。', en: 'Staking, minus the chase.', reason: '和片中奖励曲线、计数器起跳自相矛盾，「数字」所指不明。' },
  { cn: '你的 ETH，加入共识。', en: 'Conviction, meet consensus.', reason: '和 C04、C05 同一论点且更弱，「加入共识」可能被读成成为验证者，中英主语不对等。' },
]

export const method = {
  rounds: [
    { no: 'R1', title: '第一轮 · 三个方向', note: '持有者情感、产品事实、品牌记忆度三个方向各出 6 条，加上同事的 5 个主题，按六项标准打分，筛出 5 条路线不同的提案。' },
    { no: 'R2', title: '第二轮 · 加入双重价值视角', note: '老板视角、故事与角色、产品真相、社媒短句四个方向共出 34 条；每批由独立的合规与双语编辑逐条审查，保留或修改 10 条、淘汰 24 条，再和第一轮的全部内容一起去重、分类。' },
  ],
  criteria: ['故事契合', '持有者共鸣', '差异点', '合规', '中英双语', '记忆度'],
}

export const redLines = [
  '不说「赚 / Earn / 收益 / 躺赚」，不给收益率，不承诺回报',
  '不暗示质押能对冲熊市',
  '不说「安全 / 保证 / 无风险」，不暗示随时可取：原生和 Lido 都有退出等待期',
  '「复利」只做原生质押的功能名，不做标题',
  '不暗示用户自己在运行以太坊：那是独立质押',
  '对外只说「imToken 质押」「质押你的 ETH」，不提原生质押和 32 ETH，不解释质押原理的细节',
  '不暗示 ETH 会被锁住：不写锁定、锁仓、冻结、退出后才回来',
]
