// Designer Toolbox content. To open a new Confu episode: flip its status to 'open' and fill in the links.

// 设计工具图鉴 (Tool Atlas) — the page itself is generated by sources/tool-atlas/build.py into public/toolbox/atlas/
export const atlas = {
  href: '/toolbox/atlas/',
  eyebrow: 'TOOL ATLAS · 设计工具图鉴',
  title: '设计工具图鉴',
  desc: '我们推荐过的 AI 设计工具，每个工具一张大卡片：官网、适合做什么、能产出什么、第一次怎么练，以及和哪些工具搭配。支持搜索、按分类筛选，最多三个并排比较。',
  stats: [
    { value: '18', label: '工具与产品入口' },
    { value: '3', label: 'Skill 与审阅资源' },
    { value: '7', label: '分类' },
  ],
  categories: ['研究参考', '界面与网站', '图像与工作流', '视频与动效', '三维交互', 'AI 助手与开发', 'Skills 与审阅'],
  logos: [
    { name: 'Refero', src: '/toolbox/atlas/logos/refero.png' },
    { name: 'Figma', src: '/toolbox/atlas/logos/figma.svg' },
    { name: 'Framer', src: '/toolbox/atlas/logos/framer.png' },
    { name: 'Lovart', src: '/toolbox/atlas/logos/lovart.ico' },
    { name: 'Weavy', src: '/toolbox/atlas/logos/weave.svg' },
    { name: 'Higgsfield', src: '/toolbox/atlas/logos/higgsfield.png' },
    { name: 'Spline', src: '/toolbox/atlas/logos/spline.png' },
    { name: 'Rive', src: '/toolbox/atlas/logos/rive.png' },
    { name: 'Claude', src: '/toolbox/atlas/logos/claude-simpleicons.svg' },
    { name: 'ChatGPT', src: '/toolbox/atlas/logos/openai-simpleicons.svg' },
    { name: 'Gemini', src: '/toolbox/atlas/logos/gemini.png' },
    { name: 'Kimi', src: '/toolbox/atlas/logos/kimi.png' },
  ],
}

export interface EpisodeLink {
  label: string
  href: string
  kind: 'primary' | 'secondary'
  download?: boolean
}

export interface Episode {
  no: string
  date?: string
  title?: string
  subtitle?: string
  summary?: string
  tags?: string[]
  links?: EpisodeLink[]
  status: 'open' | 'soon'
}

export const series = {
  eyebrow: 'CONFU · 设计师 AI 工具箱',
  title: 'Confu 分享系列',
  desc: '面向全公司的阶段性分享，每一期讲一个用得上的 AI 工作方法，附演示文稿和资料包。新的一期讲完后会在这里开放。',
}

export const episodes: Episode[] = [
  {
    no: '02',
    date: '2026.09.24',
    title: 'Design with AI',
    subtitle: '不懂设计，也能做出世界顶级的界面。',
    summary:
      '「我是主理人」赛前培训。工具这么多，为什么做出来的东西还是很普通？分三段回答：让 AI 知道你要什么、用 Claude Design 深入细节、给 AI 建立一套多 agent 的 Loop。',
    tags: ['Claude Design', 'Refero', 'Prompt', 'Multi-agent'],
    links: [
      { label: '打开演示文稿', href: '/confu/ep02/', kind: 'primary' },
      { label: 'Claude Design 专题', href: '/confu/ep02/claude-design.html', kind: 'secondary' },
      { label: '设计质量 Loop', href: '/confu/ep02/design-loop/', kind: 'secondary' },
      { label: '下载资料包', href: '/confu/ep02/EP02-design-kit.zip', kind: 'secondary', download: true },
    ],
    status: 'open',
  },
  {
    no: '01',
    date: '2026.08.07',
    title: '会前十分钟，用 Skill 准备一次亮眼的演讲',
    subtitle: '让 AI 从项目第一天就在场，最后十分钟只是收获。',
    summary:
      '项目大脑、节点记录、把品味封装成 Skill：三个习惯，加上一个能直接用的演示文稿 Skill。',
    tags: ['Skill', 'CLAUDE.md', 'HTML Slides'],
    links: [
      { label: '打开演示文稿', href: '/confu/ep01/', kind: 'primary' },
      { label: '下载资料包', href: '/confu/ep01/Confu-EP01-resources.zip', kind: 'secondary', download: true },
    ],
    status: 'open',
  },
  { no: '03', status: 'soon' },
  { no: '04', status: 'soon' },
]

export interface Tool {
  title: string
  desc: string
  href: string
  meta: string
}

export const workflows: Tool[] = [
  {
    title: '文案管理工作流',
    desc: '从设计稿里的英文文案，到开发定义 i18n key、Figma Variables、多方审查，最后提交 PR 合并。',
    href: '/toolbox/copy-workflow/copy-workflow-final.html',
    meta: '6 个步骤',
  },
]
