(() => {
  'use strict';
  const tools = JSON.parse(document.getElementById('tool-data').textContent);
  const byId = new Map(tools.map(t => [t.id,t]));
  const categories = ['研究参考','界面与网站','图像与工作流','视频与动效','三维交互','AI助手与开发','Skills与审阅'];
  const stageIds = {
    '从零起步':['refero','mobbin','figma','chatgpt','codex','claude','claude-code','claude-artifacts','gemini','kimi'],
    '已有产品改造':['refero','mobbin','figma','codex','claude-code','claude','human-review','humanizer','rive'],
    '作品宣传':['framer','lovart','weave','higgsfield','seedance','remotion','spline','imtoken-html-slides','humanizer'],
    '找实操教程':['refero','figma','remotion','codex','imtoken-html-slides','humanizer']
  };
  const state = {category:'全部工具',stage:'全部任务',query:'',sort:'curated',selected:new Set()};
  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const external = u => /^https?:\/\//.test(u);
  const linkAttrs = u => external(u) ? ' target="_blank" rel="noopener noreferrer"' : '';
  const list = values => '<ul>'+values.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>';
  const domain = t => external(t.url) ? new URL(t.url).hostname.replace(/^www\./,'') : '本地个人插件 · Skill说明';
  const logo = t => '<span class="logo" title="'+esc(t.logoNote)+'">'+(t.logoData ? '<img src="'+t.logoData+'" alt="'+esc(t.name)+' 标识" width="64" height="64">' : '<span>'+esc(t.name.slice(0,2))+'</span>')+'</span>';
  let toastTimer, returnFocus, activeTool;
  function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;toastTimer=setTimeout(()=>$('#toast').textContent='',3200);}
  function card(t){return '<article class="tool-card" id="card-'+t.id+'" aria-labelledby="title-'+t.id+'"><div class="card-top"><div class="identity">'+logo(t)+'<div><h3 id="title-'+t.id+'">'+esc(t.name)+'</h3><div class="kind">'+esc(t.kind)+'</div></div></div><button class="compare-pick" data-select="'+t.id+'" aria-pressed="'+state.selected.has(t.id)+'" aria-label="'+(state.selected.has(t.id)?'移出比较：':'加入比较：')+esc(t.name)+'" title="最多比较3项">'+(state.selected.has(t.id)?'✓':'+')+'</button></div><div class="card-body"><p class="tagline">'+esc(t.tagline)+'</p><p class="description">'+esc(t.description)+'</p><div class="card-facts"><section class="fact"><h4>适合做什么</h4>'+list(t.bestFor)+'</section><section class="fact"><h4>能产出什么</h4>'+list(t.outputs)+'</section></div><div class="tags"><span class="tag category-tag">'+esc(t.category)+'</span>'+t.tags.slice(0,3).map(tag=>'<span class="tag">'+esc(tag)+'</span>').join('')+'</div></div><footer class="card-footer"><a class="domain" href="'+esc(t.url)+'"'+linkAttrs(t.url)+'>'+esc(domain(t))+' ↗</a><div class="card-actions"><button class="button" data-detail="'+t.id+'">使用指南</button><a class="button primary" href="'+esc(t.url)+'"'+linkAttrs(t.url)+'>'+(external(t.url)?'打开官网':'查看Skill')+' ↗</a></div></footer></article>';}
  function matches(t){const q=state.query.toLocaleLowerCase().trim();const words=q.split(/\s+/).filter(Boolean);const hay=[t.name,t.url,...t.aliases,t.tagline,t.description,t.category,t.kind,...t.tags,...t.bestFor,...t.outputs].join(' ').toLocaleLowerCase();return (state.category==='全部工具'||t.category===state.category)&&(state.stage==='全部任务'||stageIds[state.stage].includes(t.id))&&words.every(w=>hay.includes(w));}
  function render(){let found=tools.filter(matches);if(state.sort==='az')found.sort((a,b)=>a.name.localeCompare(b.name,'en'));else if(state.sort==='category')found.sort((a,b)=>categories.indexOf(a.category)-categories.indexOf(b.category));$('#grid').innerHTML=found.length?found.map(card).join(''):'<div class="empty"><h3>没有找到匹配的工具</h3><p>试试“视频”“MCP”或“界面”，也可以清除筛选。</p><button class="button primary" data-reset>清除筛选</button></div>';$('#result-title').textContent=state.category;$('#result-count').textContent='显示 '+found.length+' / '+tools.length+' 项'+(state.stage!=='全部任务'?' · '+state.stage:'')+(state.query.trim()?' · “'+state.query.trim()+'”':'');document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===state.category)));document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.stage===state.stage)));}
  function reset(){state.category='全部工具';state.stage='全部任务';state.query='';$('#search').value='';render();}
  function updateCompare(){document.querySelectorAll('[data-select]').forEach(b=>{const yes=state.selected.has(b.dataset.select);b.setAttribute('aria-pressed',String(yes));b.textContent=yes?'✓':'+';b.setAttribute('aria-label',(yes?'移出比较：':'加入比较：')+byId.get(b.dataset.select).name);});$('#compare-tray').hidden=!state.selected.size;$('#tray-count').textContent='已选 '+state.selected.size+' / 3';$('#tray-items').innerHTML=[...state.selected].map(id=>'<button class="tray-item" data-select="'+id+'" aria-label="移出比较：'+esc(byId.get(id).name)+'">'+esc(byId.get(id).name)+' ×</button>').join('');$('#compare-open').disabled=state.selected.size<2;}
  function toggleCompare(id){const wasTray=document.activeElement?.classList.contains('tray-item');if(state.selected.has(id))state.selected.delete(id);else if(state.selected.size<3)state.selected.add(id);else{toast('最多比较3项，请先移除一项。');return;}updateCompare();if(wasTray){const next=document.querySelector('[data-select="'+id+'"]');(next||$('#search')).focus();}}
  function prompt(t){return '我想用 '+t.name+' 完成一次小范围练习。\n\n练习目标：'+t.firstExercise+'\n\n我会提供：\n'+t.inputs.map((x,i)=>(i+1)+'. '+x).join('\n')+'\n\n请按这个顺序推进：\n'+t.steps.map((x,i)=>(i+1)+'. '+x).join('\n')+'\n\n先确认当前入口实际支持的能力与权限。只报告实际完成的步骤。保存输入、输出和需要继续验证的问题；不要把建议步骤说成已经执行。';}
  function openDetail(id){const t=byId.get(id);if(!t)return;activeTool=t;const d=$('#detail');if(!d.open)returnFocus=document.activeElement;$('#detail-title').textContent=t.name+' · 使用指南';$('#detail-body').innerHTML='<div class="detail-lead">'+logo(t)+'<div><h3>'+esc(t.tagline)+'</h3><p>'+esc(t.kind)+' · '+esc(t.category)+'</p></div></div><p class="detail-description">'+esc(t.description)+'</p><div class="detail-columns"><section class="detail-section"><h3>先准备这些输入</h3>'+list(t.inputs)+'</section><section class="detail-section"><h3>拿到这些产物</h3>'+list(t.outputs)+'</section></div><section class="detail-section"><h3>三步上手</h3><ol>'+t.steps.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol></section><section class="exercise"><h3>第一次，就练这个</h3><p>'+esc(t.firstExercise)+'</p><div class="prompt"><div class="prompt-head"><span>练习Prompt · 可按自己的项目改写</span><button class="button" id="copy-prompt">复制Prompt</button></div><pre id="prompt-text">'+esc(prompt(t))+'</pre><p id="copy-status" class="copy-status" role="status" aria-live="polite"></p></div></section><section class="detail-section"><h3>使用前要了解</h3>'+list(t.limits)+'</section><section class="detail-section"><h3>可以搭配</h3><div class="pair-buttons">'+t.pairs.filter(id=>byId.has(id)).map(id=>'<button class="button" data-detail="'+id+'">'+esc(byId.get(id).name)+' →</button>').join('')+'</div></section><section class="detail-section"><h3>官网与学习资料</h3><div class="source-links"><a href="'+esc(t.url)+'"'+linkAttrs(t.url)+'>'+(external(t.url)?'打开官网':'查看本地Skill说明')+' ↗</a>'+t.sources.map(s=>'<a href="'+esc(s.url)+'"'+linkAttrs(s.url)+'>'+esc(s.label)+' ↗</a>').join('')+'</div></section><div class="evidence"><p>本课记录：'+esc(t.evidence)+'</p><p>标识说明：'+esc(t.logoNote)+(t.logoSource&&external(t.logoSource)?' · <a href="'+esc(t.logoSource)+'" target="_blank" rel="noopener noreferrer">标识来源</a>':'')+'</p><p>资料整理：2026-09-24。功能开放范围与授权条件以对应入口为准。</p></div>';if(!d.open)d.showModal();d.scrollTop=0;$('#detail-close').focus();}
  function openCompare(){if(state.selected.size<2)return;const selected=[...state.selected].map(id=>byId.get(id));const rows=[['定位',t=>esc(t.tagline)],['类型',t=>esc(t.kind)],['适用任务',t=>list(t.bestFor)],['主要产物',t=>list(t.outputs)],['所需输入',t=>list(t.inputs)],['第一项练习',t=>esc(t.firstExercise)],['能力边界',t=>list(t.limits)]];$('#compare-body').innerHTML='<div class="compare-scroll" tabindex="0" aria-label="工具对照表，可横向滚动"><table class="compare-table"><thead><tr><th scope="col">比较维度</th>'+selected.map(t=>'<th scope="col">'+logo(t)+'<a href="'+esc(t.url)+'"'+linkAttrs(t.url)+'>'+esc(t.name)+' ↗</a></th>').join('')+'</tr></thead><tbody>'+rows.map(([label,fn])=>'<tr><th scope="row">'+label+'</th>'+selected.map(t=>'<td>'+fn(t)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';$('#compare-dialog').showModal();$('#compare-close').focus();}
  async function copyPrompt(){const text=prompt(activeTool);try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(text);$('#copy-status').textContent='练习Prompt已复制。';}catch{const range=document.createRange();range.selectNodeContents($('#prompt-text'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);let ok=false;try{ok=document.execCommand('copy');}catch{}$('#copy-status').textContent=ok?'练习Prompt已复制。':'已选中文本，请按⌘C或Ctrl+C复制。';}}
  $('#categories').innerHTML=['全部工具',...categories].map(c=>'<button class="category" data-category="'+c+'" aria-pressed="'+(c==='全部工具')+'"><span>'+c+'</span><span>'+String(c==='全部工具'?tools.length:tools.filter(t=>t.category===c).length).padStart(2,'0')+'</span></button>').join('');
  $('#stages').innerHTML='<span>按当前任务</span>'+['全部任务',...Object.keys(stageIds)].map(s=>'<button class="filter" data-stage="'+s+'" aria-pressed="'+(s==='全部任务')+'">'+s+'</button>').join('');
  $('#tool-total').textContent=tools.length+' TOOLS';
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-category')){state.category=b.dataset.category;render();}else if(b.hasAttribute('data-stage')){state.stage=b.dataset.stage;render();}else if(b.hasAttribute('data-detail'))openDetail(b.dataset.detail);else if(b.hasAttribute('data-select'))toggleCompare(b.dataset.select);else if(b.hasAttribute('data-reset'))reset();else if(b.id==='compare-open')openCompare();else if(b.id==='compare-clear'){const id=[...state.selected][0];state.selected.clear();updateCompare();(document.querySelector('[data-select="'+id+'"]')||$('#search')).focus();}else if(b.id==='detail-close')$('#detail').close();else if(b.id==='compare-close')$('#compare-dialog').close();else if(b.id==='copy-prompt')copyPrompt();});
  $('#search').addEventListener('input',e=>{state.query=e.target.value;render();});$('#sort').addEventListener('change',e=>{state.sort=e.target.value;render();});
  $('#detail').addEventListener('close',()=>{if(returnFocus?.isConnected)returnFocus.focus();else $('#search').focus();});
  document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}));
  document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!document.querySelector('dialog[open]')&&!e.target.closest('input,textarea,select,[contenteditable=true]')){e.preventDefault();$('#search').focus();}});
  render();
  const initial=location.hash.match(/^#tool=([a-z-]+)$/);if(initial&&byId.has(initial[1]))openDetail(initial[1]);
})();
